#############################################################################
# Makefile for building: themessenger
# Generated by qmake (2.01a) (Qt 4.4.0) on: Sun Oct 26 20:15:21 2008
# Project:  themessenger.pro
# Template: app
# Command: /root/Desktop/qt-x11-opensource-src-4.4.0/bin/qmake -unix -o Makefile themessenger.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include -I. -IInterface -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.0/lib -lQtGui -L/usr/local/Trolltech/Qt-4.4.0/lib -L/usr/X11R6/lib -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /root/Desktop/qt-x11-opensource-src-4.4.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = BuddyList.cpp \
		login.cpp \
		magic_shit.cpp \
		main.cpp \
		md5.c \
		priorityQueue.cpp \
		sha.c \
		socket.cpp \
		thread.cpp \
		yinstance.cpp \
		ypacket.cpp \
		Interface/BuddyList.cpp \
		Interface/FeelerGui.cpp \
		Interface/Login.cpp \
		Interface/main.cpp moc_yinstance.cpp \
		moc_FeelerGui.cpp
OBJECTS       = BuddyList.o \
		login.o \
		magic_shit.o \
		main.o \
		md5.o \
		priorityQueue.o \
		sha.o \
		socket.o \
		thread.o \
		yinstance.o \
		ypacket.o \
		BuddyList.o \
		FeelerGui.o \
		Login.o \
		main.o \
		moc_yinstance.o \
		moc_FeelerGui.o
DIST          = /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		themessenger.pro
QMAKE_TARGET  = themessenger
DESTDIR       = 
TARGET        = themessenger

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: themessenger.pro  /usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile themessenger.pro
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile themessenger.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/themessenger1.0.0 || $(MKDIR) .tmp/themessenger1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/themessenger1.0.0/ && $(COPY_FILE) --parents action.h bits.h buddy.h BuddyList.h config.h login.h magic_shit.h md5.h message_base.h priorityQueue.h sha.h socket.h thread.h unix_std_space.h yinstance.h ypacket.h Interface/BuddyList.h Interface/FeelerGui.h Interface/Login.h .tmp/themessenger1.0.0/ && $(COPY_FILE) --parents BuddyList.cpp login.cpp magic_shit.cpp main.cpp md5.c priorityQueue.cpp sha.c socket.cpp thread.cpp yinstance.cpp ypacket.cpp Interface/BuddyList.cpp Interface/FeelerGui.cpp Interface/Login.cpp Interface/main.cpp .tmp/themessenger1.0.0/ && (cd `dirname .tmp/themessenger1.0.0` && $(TAR) themessenger1.0.0.tar themessenger1.0.0 && $(COMPRESS) themessenger1.0.0.tar) && $(MOVE) `dirname .tmp/themessenger1.0.0`/themessenger1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/themessenger1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_yinstance.cpp moc_FeelerGui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_yinstance.cpp moc_FeelerGui.cpp
moc_yinstance.cpp: socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h \
		login.h \
		action.h \
		BuddyList.h \
		buddy.h \
		priorityQueue.h \
		yinstance.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) yinstance.h -o moc_yinstance.cpp

moc_FeelerGui.cpp: Interface/FeelerGui.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) Interface/FeelerGui.h -o moc_FeelerGui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

BuddyList.o: BuddyList.cpp BuddyList.h \
		buddy.h \
		ypacket.h \
		message_base.h \
		bits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BuddyList.o BuddyList.cpp

login.o: login.cpp login.h \
		ypacket.h \
		message_base.h \
		bits.h \
		action.h \
		socket.h \
		unix_std_space.h \
		config.h \
		BuddyList.h \
		buddy.h \
		md5.h \
		sha.h \
		magic_shit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

magic_shit.o: magic_shit.cpp magic_shit.h \
		md5.h \
		sha.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o magic_shit.o magic_shit.cpp

main.o: main.cpp socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h \
		login.h \
		action.h \
		BuddyList.h \
		buddy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

md5.o: md5.c config.h \
		md5.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o md5.c

priorityQueue.o: priorityQueue.cpp priorityQueue.h \
		action.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o priorityQueue.o priorityQueue.cpp

sha.o: sha.c sha.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha.o sha.c

socket.o: socket.cpp socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socket.o socket.cpp

thread.o: thread.cpp thread.h \
		action.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

yinstance.o: yinstance.cpp yinstance.h \
		socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h \
		login.h \
		action.h \
		BuddyList.h \
		buddy.h \
		priorityQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yinstance.o yinstance.cpp

ypacket.o: ypacket.cpp ypacket.h \
		message_base.h \
		bits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ypacket.o ypacket.cpp

BuddyList.o: Interface/BuddyList.cpp Interface/BuddyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BuddyList.o Interface/BuddyList.cpp

FeelerGui.o: Interface/FeelerGui.cpp Interface/FeelerGui.h \
		Interface/BuddyList.h \
		Interface/Login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FeelerGui.o Interface/FeelerGui.cpp

Login.o: Interface/Login.cpp Interface/Login.h \
		yinstance.h \
		socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h \
		login.h \
		action.h \
		BuddyList.h \
		buddy.h \
		priorityQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Login.o Interface/Login.cpp

main.o: Interface/main.cpp Interface/FeelerGui.h \
		yinstance.h \
		socket.h \
		unix_std_space.h \
		config.h \
		message_base.h \
		ypacket.h \
		bits.h \
		login.h \
		action.h \
		BuddyList.h \
		buddy.h \
		priorityQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Interface/main.cpp

moc_yinstance.o: moc_yinstance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yinstance.o moc_yinstance.cpp

moc_FeelerGui.o: moc_FeelerGui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FeelerGui.o moc_FeelerGui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

