######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 1 23:54:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BuddyList.h FeelerGui.h Login.h
SOURCES += BuddyList.cpp FeelerGui.cpp Login.cpp main.cpp
